grails:
    profile: web-plugin
    codegen:
        defaultPackage: uk.co.desirableobjects.sendgrid
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
